### ISSUE TITLE
DS3 crashes when using the modded steam_api file

### ISSUE THREAD

**Issue by craspid** [tremwil/DS3ConnectionInfo#12]
DS3 crashes on startup before the game window even shows up when I use the provided steam_api64.dll from the mod.

I've tried running the game without mods (wex dust and honest merchant) but seems to still crash,
also tried using the original steam_api file and tried launching but this time the program crashes instead of DS3 with an "Unhandled Exception" error mentioning the steam_api64.dll,
I've already tried adding the program and the entire DS3 game folder to my AV's exclusion list as well but it doesn't seem to do anything with the modded and original steam_api.

**Comment by tremwil** [comment]
It sounds like you're trying to copy the program's files into the game folder. This is a standalone application; you're not supposed to do that. Extract the zip file somewhere else on your computer.

**Comment by tremwil** [comment]
FYI the reason for the crash is that the steam API version used by the program is different from the older one used by DS3.

**Comment by craspid** [comment]
Thanks for the quick response, didn't realize it was a standalone. Seems to work perfectly now
