### ISSUE TITLE
Region Listed as ", Singapore"

### ISSUE THREAD

**Issue by beetlejuiceee** [tremwil/DS3ConnectionInfo#2]
So the city-state was blank. Not a huge deal but just letting you know.

EDIT: Removed Steam profile link

**Comment by tremwil** [comment]
Noted. This is due to locations in Singapore not being given a state/region by the geolocation API I use. I won't publish a new version for a minor graphical bug like this, so I'll leave the issue open until I have enough new features ready to justify a new release.

**Comment by beetlejuiceee** [comment]
Appreciated, thanks for the response.

**Comment by tremwil** [comment]
Fixed in V4.
