### ISSUE TITLE
Doesnt scale right with dpi. 

### ISSUE THREAD

**Issue by AnmerSeif** [tremwil/DS3ConnectionInfo#3]
Overlay will be placed outside the screen if you have 125% dpi.

Is it possible to add "fixed" position option in "settings.txt", so the overlay can be placed according to the screens dimensions instead of the "dark souls III" window?

**Comment by AnmerSeif** [comment]
One solution is to divide Left, Top, width and height with dpi, however I am not sure if its the most optimized method.

https://github.com/tremwil/DS3ConnectionInfo/blob/48f60946827fd60d1c97917c475ca963bb90de56/DS3ConnectionInfo/OverlayWindow.xaml.cs#L144-L148

```   
      double dpi = System.Windows.PresentationSource.FromVisual(this).CompositionTarget.TransformToDevice.M11;
      Left = targetRect.x1 / dpi;
      Top = targetRect.y1 / dpi;
      Width = (targetRect.x2 - targetRect.x1) / dpi;
      Height = (targetRect.y2 - targetRect.y1) / dpi;
```

**Comment by tremwil** [comment]
Fixed in V4.
