### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by beetlejuiceee** [tremwil/DS3ConnectionInfo#5]
https://github.com/tremwil/DS3ConnectionInfo/releases/download/V4.0/DS3ConnectionInfo-V4.0.zip is a dead link. And I don't have the dev tools installed to compile the project. I'm sure you will correct. Thanks.

**Comment by tremwil** [comment]
Sorry, I updated the release tag without changing the link. Should be fixed now.

**Comment by beetlejuiceee** [comment]
It works now
