### ISSUE TITLE
Can't Launch Program

### ISSUE THREAD

**Issue by Misaki2D** [tremwil/DS3ConnectionInfo#8]
Whenever I try to open the program while ds3 is running it will crash. I have also opened it while it wasn't running, and it worked fine until I launch ds3.

**Comment by tremwil** [comment]
What other third party programs are you using with DS3? I will try replicating the issue, and if I can't I'll upload a debug version of the program which you can use to submit exception logs.

**Comment by Misaki2D** [comment]
I use CE with ds3 but I tried running it without but still same issue. I have some mods installed, i'm not sure if that could cause an issue, but I remember having the same issue with a previous version but one day it fixed itself.

**Comment by Misaki2D** [comment]
Ok so I figured out what was wrong. My anti-virus was blocking the program. Thanks for quick response tho.

**Comment by tremwil** [comment]
Thanks for the heads up. I didn't think I'd trip any AV flags since the Windows API stuff I use isn't that uncommon, but I guess an overly strict AV might still flag it. I'll add a notice in the readme to warn people about potential AV interference.
